---
title: "R Notebook"
date: April 6, 2018
output:
  html_document:
    theme: journal
---

# Reading in datasets and loading packages:

```{r, warning=FALSE, message=FALSE}
# Loading packages
library("ggplot2")
library('vegan')
library('dplyr')

# Setting working directory
setwd("C:/Users/ebatz/Box Sync/Eviner lab shared/Evan/Research Projects/Julia BetaDiv")

# load data
data<-read.csv("Vernal_data_final.csv", stringsAsFactors=FALSE)
data$Year<-as.factor(data$Year)

# Remove bare ground
data <- data %>%
  select(-(BarGr))

# Group by zone
by.zone <- data %>% 
  group_by(Site.ID, Grazing, Year, Zone) %>% 
  summarise_if(is.numeric, mean)

# Group by pool
by.pool <- data %>% 
  group_by(Site.ID, Grazing, Year) %>% 
  summarise_if(is.numeric, mean)
```

# PerMANOVA tables:

```{r}
#################################Comparing zones################################

# Setting what dataset will be used to compare:
data_adonis = by.zone
vd <- vegdist(data_adonis[,5:ncol(by.zone)], 
              na.rm=T, 
              method='bray') #bray

# Running permanova on individual datasets
permanova <- adonis2(vd ~ (Grazing + Zone + Year) * (Grazing + Zone + Year), 
                    data = data_adonis)
permanova
```

```{r}
#################################Comparing zones################################

# Setting what dataset will be used to compare:
data_adonis = by.pool
vd <- vegdist(data_adonis[,5:ncol(by.pool)], 
              na.rm=T, 
              method='bray') #bray

# Running permanova on individual datasets
permanova <- adonis2(vd ~ Grazing * Year, 
                    data = data_adonis)
permanova
```

# Visualization

## NMDS Plot of Zones:

```{r}

data_adonis = by.zone

nmds_run = metaMDS(data_adonis[,6:ncol(data_adonis)],
               try = 50,
               trymax = 100,
               trace = FALSE
               )

data_adonis$GrazingZone = paste(data_adonis$Grazing, data_adonis$Zone)
data_adonis$group = as.factor(data_adonis$GrazingZone)
NMDS = bind_cols(data.frame(nmds_run$points), group = as.factor(c(data_adonis$group)))
NMDS.mean=aggregate(NMDS[,1:2], list(group=NMDS$group),mean)

# Calculating the shape of the ellipses
veganCovEllipse<-function (cov, center = c(0, 0), scale = 1, npoints = 100){
    theta <- (0:npoints) * 2 * pi/npoints
    Circle <- cbind(cos(theta), sin(theta))
    t(center + scale * t(Circle %*% chol(cov)))
}

df_ell <- data.frame()
for(g in levels(NMDS$group)){
  df_ell <- rbind(df_ell, cbind(as.data.frame(with(NMDS[NMDS$group==g,],
                  veganCovEllipse(cov.wt(cbind(MDS1,MDS2),
                                          wt=rep(1/length(MDS1),length(MDS1)))$cov,
                                  center=c(mean(MDS1),mean(MDS2)))))
                  ,group=g))
}

# Adding other details for facetting
NMDS = right_join(NMDS, bind_cols(group = as.character(as.numeric(data_adonis$group)), data_adonis[,2:4]),
                      by = "group")

NMDS.mean = inner_join(NMDS.mean, bind_cols(group = as.character(as.numeric(data_adonis$group)), data_adonis[,2:4]),
                      by = "group")
NMDS.mean = NMDS.mean[!duplicated(NMDS.mean[,2:5]),]

df_ell = right_join(df_ell, bind_cols(group = as.character(as.numeric(data_adonis$group)), data_adonis[,2:4]),
                      by = "group")
```

Edit the parameters here to make the figure prettier:

```{r}
# Producing figure
ggplot(data = NMDS, aes(MDS1, MDS2)) + 
  geom_point(aes(shape = Zone), alpha = .5) +
  scale_shape(solid = FALSE) + 
  geom_path(data = df_ell, aes(x=MDS1, y=MDS2, group = Zone), size=1, linetype=1) +
  geom_text(data = NMDS.mean, aes(label = NMDS.mean$Zone)) + 
  facet_wrap(~Grazing) +
  theme_bw()+ 
  geom_text(data = data.frame(MDS1 = .95, MDS2 = -1.05, Grazing = "Ungrazed"), 
            aes(label = paste("Stress:", round(nmds_run$stress, 2))),
            fontface = "bold")
```

## NMDS plot for combined pools:

```{r, warning=FALSE, message=FALSE}
library(JostDiv); library(tidyverse); library(testthat)

data_adonis = by.pool

nmds_run = metaMDS(data_adonis[,5:ncol(data_adonis)],
               try = 50,
               trymax = 100,
               trace = FALSE,
               distance = "jaccard",
               binary = TRUE
               )

data_adonis$group = as.factor(paste(data_adonis$Grazing, data_adonis$Year))
NMDS = bind_cols(data.frame(nmds_run$points), group = as.factor(c(data_adonis$group)))
NMDS.mean=aggregate(NMDS[,1:2], list(group=NMDS$group),mean)

# Calculating the shape of the ellipses
veganCovEllipse<-function (cov, center = c(0, 0), scale = 1, npoints = 100){
    theta <- (0:npoints) * 2 * pi/npoints
    Circle <- cbind(cos(theta), sin(theta))
    t(center + scale * t(Circle %*% chol(cov)))
}

df_ell <- data.frame()
for(g in levels(NMDS$group)){
  df_ell <- rbind(df_ell, cbind(as.data.frame(with(NMDS[NMDS$group==g,],
                  veganCovEllipse(cov.wt(cbind(MDS1,MDS2),
                                          wt=rep(1/length(MDS1),length(MDS1)))$cov,
                                  center=c(mean(MDS1),mean(MDS2)))))
                  ,group=g))
}

# Adding other details for facetting
NMDS = right_join(NMDS, bind_cols(group = as.character(as.numeric(data_adonis$group)), data_adonis[,2:3]),
                      by = "group")

NMDS.mean = right_join(NMDS.mean, bind_cols(group = as.character(as.numeric(data_adonis$group)), data_adonis[,2:3]),
                      by = "group")

NMDS.mean = NMDS.mean[!duplicated(NMDS.mean[,2:5]),]

NMDS.mean = NMDS.mean[order(NMDS.mean$Year),]

df_ell = right_join(df_ell, bind_cols(group = as.character(as.numeric(data_adonis$group)), data_adonis[,2:3]),
                      by = "group")
```

Edit the parameters here to make the figure prettier:

```{r}
# Producing figure
ggplot(data = NMDS, aes(MDS1, MDS2)) + 
  geom_point(aes(shape = Grazing), alpha = .5) +
  scale_shape(solid = FALSE) + 
  geom_path(data = df_ell, aes(x=MDS1, y=MDS2, group = Grazing), size=1, linetype=1) +
  geom_text(data = NMDS.mean, aes(label = NMDS.mean$Grazing)) +
  theme_bw() +
  facet_wrap(~Year) + 
  geom_text(data = data.frame(MDS1 = 0.5, MDS2 = -0.6, Year = 2017), 
            aes(label = paste("Stress:", round(nmds_run$stress, 2))),
            fontface = "bold")
```

# Beta-Dispersion Tests:

__Jaccard dissimilarity of pools__

```{r}
bd <- betadisper(vegdist(by.pool[,5:ncol(by.pool)], 
                         method = "jaccard", 
                         binary = TRUE),
                 paste(by.pool$Grazing, by.pool$Year))
boxplot(bd)
TukeyHSD(bd)
```
__Bray-Curtis dissimilarity of pools__

```{r}
bd <- betadisper(vegdist(by.pool[,5:ncol(by.pool)], 
                         method = "bray"),
                 paste(by.pool$Grazing, by.pool$Year))
boxplot(bd)
TukeyHSD(bd)
```
